language: php

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0

addons:
  postgresql: 9.3

env:
 global:
  - IGNORE_NAMES=package.json,gulpfile.js
  - IGNORE_PATHS=amd/build/accordion.min.js
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE

matrix:
  exclude:
    - php: 5.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 5.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 5.5
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 5.5
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 5.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 5.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 5.5
      env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 5.5
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE

before_install:
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
